const categoryIndex = { Railways: 0, Banking: 1, Defence: 2, Teaching: 3, SSC: 4, Police: 5, 'State Government': 6, Engineering: 7, Healthcare: 8 }
const categoryJobs = { Banking: '12,450 Jobs', Defence: '8,745 Jobs', Engineering: '15,230 Jobs', Healthcare: '6,398 Jobs', Police: '9,862 Jobs', Railways: '13,158 Jobs', SSC: '18,256 Jobs', 'State Government': '25,478 Jobs', Teaching: '11,325 Jobs' }
const examIndex = { 'Demo SSC CHSL': 0, 'Demo Bank PO': 1, 'Demo RRB NTPC': 2, 'Demo State PET': 3 }
function Sprite({ pack, index = 0, grid = false, row = 0 }) { const x = pack === 'metric' ? `${index * 20}%` : grid ? `${(index % 3) * 50}%` : `${index * 33.333}%`; const y = grid && pack !== 'metric' ? `${Math.floor(index / 3) * 50}%` : `${row ? 100 : 0}%`; return <span className={`sprite-icon sprite-${pack}`} style={{ backgroundPosition: `${x} ${y}` }} aria-hidden="true" /> }
export function SectionHeader({ title, link }) {
  const isJobsLink = link === 'View All Jobs'
  return <div className="section-heading"><h2>{isJobsLink ? 'Latest Jobs' : title}</h2>{isJobsLink ? <Link to="/jobs">{link} →</Link> : <a href="#content">{link} →</a>}</div>
}
export function QuickAccessCard({ item }) { return <a href="#content" className="quick-card"><span className="quick-icon">{item.icon}</span><span><strong>{item.title}</strong><small>{item.detail}</small></span></a> }
export function RecruitmentCard({ job }) { return <article className="recruitment-card"><span className={'job-badge ' + (job.badge === 'HOT' ? 'hot' : '')}>{job.badge}</span><div className="recruitment-main"><img className="emblem-image" src="/assets/generated-recruitment-seal.png" alt="" /><div><h3>{job.title}</h3><p>{job.organization}</p><strong>{job.posts}</strong><p>{job.qualification}</p><p><b>Last Date:</b> {job.deadline}</p></div></div><button>Apply Now</button></article> }
export function AdBanner() { return <aside className="ad-banner"><span className="ad-label">Advertisement</span><div><small>Boost Your Preparation with</small><strong>Top Study Materials</strong><p>Books | Mock Tests | Online Courses</p></div><button>Explore Now</button></aside> }
export function CategoryCard({ category }) { return <a className="category-card" href="#content"><Sprite pack="category" index={categoryIndex[category[1]]} grid /><strong>{category[1]}</strong><small>{categoryJobs[category[1]] || 'All Categories'}</small></a> }
export function ExamCard({ exam }) { const [count] = exam.left.split(' '); return <article className="exam-card"><Sprite pack="flat" index={examIndex[exam.name]} /><div><h3>{exam.name}</h3><p>{exam.type}</p><time>{exam.date}</time></div><span className="days"><b>▣ {count}</b><small>Days Left</small></span></article> }
export function UpdateItem({ update }) { const index = update.status === 'result' ? 1 : update.status === 'answer key' ? 2 : update.status === 'exam date' ? 3 : 0; return <article className="update-item"><Sprite pack="flat" index={index} row={1} /><div><h3>{update.title}</h3><p>{update.status}</p></div><time>{update.time}</time></article> }
export function TrustStats({ stats }) { return <section className="trust-strip" aria-label="Trusted by millions of aspirants"><span className="trust-prefix">Trusted by Millions of Aspirants</span>{stats.map(([, value, label], index) => <div key={label}><Sprite pack="metric" index={index} /><strong>{value}</strong><small>{label}</small></div>)}</section> }
import { Link } from 'react-router-dom'
