const paths = {
  search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>, filter: <path d="M4 5h16l-6 7v5l-4 2v-7Z"/>,
  sort: <><path d="M5 6h10M5 12h7M5 18h4"/><path d="m16 15 3 3 3-3M19 18V6"/></>, briefcase: <><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V4h8v3M3 12h18"/></>,
  calendar: <><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></>, pin: <><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></>,
  bookmark: <path d="M6 3h12v18l-6-4-6 4Z"/>, cap: <><path d="m2 9 10-5 10 5-10 5Z"/><path d="M6 11v5c3 3 9 3 12 0v-5"/></>, users: <><circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-7 6-7s6 3 6 7M16 6c3 0 4 4 2 6M17 14c3 1 4 3 4 6"/></>,
}
export function Icon({ name, size = 16 }) { return <svg className="line-icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg> }
export function JobsStats({ stats }) { const items = [['total','Total Jobs','briefcase'],['open','Open Jobs','calendar'],['upcoming','Upcoming Jobs','calendar'],['closing_soon','Closing Soon','calendar']]; return <section className="jobs-stats" aria-label="Job statistics">{items.map(([key,label,icon],i)=><article key={key}><span className={`stat-icon stat-${i}`}><Icon name={icon}/></span><span><small>{label}</small><strong>{Number(stats[key]||0).toLocaleString('en-IN')}</strong></span></article>)}</section> }
export function JobFilters({ values, options, onChange, onReset, mobile=false, onClose }) {
  return <form className={`job-filters ${mobile?'mobile-filters':''}`} onSubmit={e=>e.preventDefault()}><div className="filter-title"><strong>Filters</strong><button type="button" onClick={onReset}>Clear All</button>{mobile&&<button type="button" className="drawer-close" onClick={onClose} aria-label="Close filters">×</button>}</div>
    <label className="filter-field"><span>Keyword</span><div className="filter-search"><input value={values.search||''} onChange={e=>onChange('search',e.target.value)} placeholder="Search jobs, organizations..."/><Icon name="search"/></div></label>
    <Select label="Category" name="category" value={values.category} onChange={onChange} placeholder="Select Category" items={options.categories?.map(x=>[x.slug,x.name])}/><Select label="Organization" name="organization" value={values.organization} onChange={onChange} placeholder="Select Organization" items={options.organizations?.map(x=>[x.slug,x.name])}/><Select label="Qualification" name="qualification" value={values.qualification} onChange={onChange} placeholder="Select Qualification" items={options.qualifications?.map(x=>[x,x])}/><Select label="State / Location" name="state" value={values.state} onChange={onChange} placeholder="Select State" items={options.locations?.map(x=>[x,x])}/>
    <fieldset><legend>Job Status</legend>{[['','All'],['open','Open'],['upcoming','Upcoming'],['closed','Closed']].map(([value,label])=><label className="radio-row" key={label}><input type="radio" name={`status-${mobile}`} checked={(values.status||'')===value} onChange={()=>onChange('status',value)}/> {label}</label>)}</fieldset>
    <Select label="Date Posted" name="date_posted" value={values.date_posted} onChange={onChange} placeholder="Any Time" items={[["24h","Last 24 Hours"],["7d","Last 7 Days"],["30d","Last 30 Days"]]}/></form>
}
function Select({label,name,value,onChange,placeholder,items=[]}) { return <label className="filter-field"><span>{label}</span><select value={value||''} onChange={e=>onChange(name,e.target.value)}><option value="">{placeholder}</option>{items.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label> }
export function JobCard({job}) { const age=job.age_min&&job.age_max?`${job.age_min}–${job.age_max} Years`:null; const urgent=job.job_status==='open'&&job.days_remaining<=7; return <article className={`job-list-card ${job.job_status==='closed'?'closed-job':''}`}><div className="job-logo" aria-hidden="true">{job.organization_icon||'🏛'}</div><div className="job-card-main"><div className="job-card-heading"><div><h2>{job.title}</h2><p>{job.organization}</p></div><button className="bookmark-button" disabled aria-label="Bookmark feature coming soon"><Icon name="bookmark"/></button></div><div className="job-meta"><span><Icon name="briefcase"/>{Number(job.total_vacancies).toLocaleString('en-IN')} Posts</span><span><Icon name="cap"/>{job.qualification}</span>{age&&<span><Icon name="users"/>{age}</span>}<span><Icon name="pin"/>{job.location}</span></div><div className="job-published"><b className={job.status==='closing'?'hot-badge':''}>{job.status==='closing'?'HOT':'NEW'}</b><span>Posted {job.published_display.toLowerCase()}</span></div></div><div className="job-card-action"><p>Last Date <strong>{job.last_date}</strong></p>{urgent&&<small>Closing in {job.days_remaining} day{job.days_remaining===1?'':'s'}</small>}<a href={job.application_url||'#'}>{job.job_status==='closed'?'View Details':'Apply Now'}</a></div></article> }
export function JobsPagination({page,totalPages,onPage}) { if(totalPages<=1)return null; const pages=Array.from(new Set([1,page-1,page,page+1,totalPages])).filter(x=>x>0&&x<=totalPages).sort((a,b)=>a-b); return <nav className="jobs-pagination" aria-label="Jobs pagination"><button disabled={page===1} onClick={()=>onPage(page-1)} aria-label="Previous page">‹</button>{pages.map((x,i)=><span key={x}>{i>0&&x-pages[i-1]>1&&<i>…</i>}<button className={page===x?'active':''} aria-current={page===x?'page':undefined} onClick={()=>onPage(x)}>{x}</button></span>)}<button disabled={page===totalPages} onClick={()=>onPage(page+1)} aria-label="Next page">›</button></nav> }
